---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# BobRoss

Welcome to the **BobRoss** R package! This package provides data from Bob Ross's *Joy of Painting* and includes a Shiny app to analyze the colors used in his famous paintings. Dive into the vibrant world of Bob Ross and explore how he used different colors across his paintings.

## Package Overview

The **BobRoss** package contains:
- A dataset that captures the color information from all of Bob Ross's paintings featured in the *Joy of Painting* series.
- A Shiny app that allows you to visualize and interactively explore the colors used in these paintings.

## Installation

To install the **BobRoss** package, you can use the following command to install it directly from GitHub:

```r
# Install devtools package if you don't have it
install.packages("devtools")

# Install BobRoss package from GitHub
devtools::install_github("ETC5523-2024/assignment-4-packages-and-shiny-apps-Raodityaaa/BobRoss")
```

# Example usage:
```r
library(BobRoss)
loadbob()
```

# License
This package is licensed under the MIT License. See the LICENSE file for more details.

Enjoy exploring the colorful world of Bob Ross's paintings!
